---
- hosts: localhost
  vars:
    key_path: "/home/vagrant/ansible-demo/ssl/apache-selfsigned.key"
    cert_path: "/home/vagrant/ansible-demo/ssl/apache-selfsigned.crt"
    csr_path: "/home/vagrant/ansible-demo/ssl/{{ ansible_eth0.ipv4.address }}.csr"
  tasks:
    - name: Create directory for private_key
      file: path="{{ key_path | dirname }}" state=directory mode=0700
    - name: Create directory for csr
      file: path="{{ csr_path | dirname }}" state=directory 
    - name: Create directory for certificate
      file: path="{{ cert_path | dirname }}" state=directory 
    - name: Copy private key to server
      # openssl_privatekey: path="{{ key_path }}"
      copy: src="{{ key_path | basename }}"  dest="{{ key_path }}" mode=0600
    - name: Create csr
      openssl_csr:
        path: "{{ csr_path }}"
        privatekey_path: "{{ key_path }}"
        common_name: "{{ ansible_eth0.ipv4.address }}"
    - name: Create OpenSSL certificate
      openssl_certificate:
        path: "{{ cert_path }}"
        privatekey_path: "{{ key_path }}"
        csr_path: "{{ csr_path }}"
        provider: "selfsigned"
        selfsigned_not_after: "20201231120000Z"

