---
- hosts: node1
  become: yes
  vars:
    ssl_conf_path: /etc/httpd/conf.d/ssl.conf
    key_path: "/etc/ssl/private/apache-selfsigned.key"
    cert_path: "/etc/ssl/certs/apache-selfsigned.crt"
    redirect_conf: "/etc/apache2/sites-available/000-default.conf"
  tasks:
    - name: Copy ssl config to server
      template: src=ssl.conf.j2 dest="{{ ssl_conf_path }}"
      notify: restart_apache
    - name: Copy config to redirect requests on port 80
      template: src=000-default-conf.j2 dest="{{ redirect_conf }}"
  handlers:
    - name: Restart Apache
      service: name=httpd state=restarted
      listen: restart_apache
