---
- hosts: nodes
  become: yes
  tasks:
    - name: Create directory for private_key
      file: path=/etc/ssl/private state=directory mode=0700
    - name: Create directory for csr
      file: path=/etc/ssl/csr state=directory 
    - name: Create directory for certificate
      file: path=/etc/ssl/certs state=directory 
    - name: Create private key
      openssl_privatekey: path=/etc/ssl/private/apache-selfsigned.key
    - name: Create csr
      openssl_csr:
        path: /etc/ssl/csr/{{ ansible_eth0.ipv4.address }}.csr
        privatekey_path: /etc/ssl/private/apache-selfsigned.key
        common_name: "{{ ansible_eth0.ipv4.address }}"
    - name: Create OpenSSL certificate
      openssl_certificate:
        path: /etc/ssl/certs/apache-selfsigned.crt
        private_key_path: /etc/ssl/private/apache-selfsigned.key
        csr_path: /etc/ssl/csr/{{ ansible_eth0.ipv4.address }}.csr
        provider: selfsigned
