---
- hosts: node1
  become: yes
  tasks:
    - name: Add repository
      yum_repository: name=epel description="EPEL YUM repo" baseurl=https://download.fedoraproject.org/pub/epel/$releasever/$basearch/ gpgcheck=no
    - name: Install Pip
      yum: name=python2-pip state=installed
    - name: Install Pyopenssl
      pip: name=pyopenssl
    - name: Create directory for private_key
      file: path=/etc/ssl/private state=directory mode=0700
    - name: Create directory for csr
      file: path=/etc/ssl/csr state=directory 
    - name: Create directory for certificate
      file: path=/etc/ssl/certs state=directory 
    - name: Create private key
      openssl_privatekey: path=/etc/ssl/private/apache-selfsigned.key
    - debug: msg="{{ ansible_enp0s8.ipv4.address }}"
    - name: Create csr
      openssl_csr:
        path: /etc/ssl/csr/{{ ansible_enp0s8.ipv4.address }}.csr
        privatekey_path: /etc/ssl/private/apache-selfsigned.key
        common_name: "{{ ansible_enp0s8.ipv4.address }}"
    - name: Create OpenSSL certificate
      openssl_certificate:
        path: /etc/ssl/certs/apache-selfsigned.crt
        privatekey_path: /etc/ssl/private/apache-selfsigned.key
        csr_path: /etc/ssl/csr/{{ ansible_enp0s8.ipv4.address }}.csr
        provider: selfsigned
