---
- hosts: web
  become: yes
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: installed
    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Set Apache config to listen to port 8080
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen'
        insertafter: '^#Listen'
        line: 'Listen 0.0.0.0:8080'
      notify: restart webserver
    - name: Unarchive website content
      unarchive:
        src: /home/dennis/website.tgz
        dest: /var/www/html
    - name: Enable http in firewall config
      firewalld:
        service: http
        state: enabled
        permanent: yes
      notify: restart firewall
    - name: Enable tcp port 8080 in firewall config
      firewalld:
        port: 8080/tcp
        state: enabled
        permanent: yes
      notify: restart firewall
  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
      listen: 'restart webserver'
    - name: Restart Firewall
      service:
        name: firewalld
        state: restarted
      listen: 'restart firewall'
