---
# tasks file for website
- name: Install Apache
  yum: name=httpd state=installed
- name: Start and enable Apache
  service: name=httpd state=started enabled=yes
- name: Set Apache config to listen to port 8080
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen'
    insertafter: '^#Listen'
    line: 'Listen 0.0.0.0:8080'
  notify: restart webserver
- name: Unarchive website content
  unarchive: src=website.tgz dest=/var/www/html
- name: Enable http and https in firewall config
  firewalld: service="{{item}}" state=enabled permanent=yes
  loop:
    - http
    - https
  notify: restart firewall
- name: Enable tcp port 8080 and 443 in firewall config
